### ISSUE TITLE
Implement callback

### ISSUE THREAD

**Issue by perandre** [front/smspay-woocommerce#2]
Still after checkout went thru, I can see the product is still On Hold in backend http://smspay.dev1.nextlogic.ro/wp-admin/post.php?post=29&action=edit

 In SMSpay admin however, it is completed: http://inft.ly/hGcUz68

**Comment by ovidiu-ciobanu** [comment]
Fixed issue. It was a problem from documentation the plugin was checking for "COMPLETE" and was receiving "COMPLETED"
